### ISSUE TITLE
Build failed!

### ISSUE THREAD

**Issue by Anan5a** [hypersad/atom-armv7l#12]
## The build was failed with following error 
```root@localhost:~/atom-armv7l# node script/build
Node:   v6.10.3
Npm:    v3.10.5
Installing script dependencies
Installing apm
./bin/npm: line 13: /root/atom-armv7l/apm/node_modules/atom-package-manager/bin/../node_modules/.bin/npm: No such file or directory
module.js:327
    throw err;
    ^

Error: Cannot find module '../build/Release/git.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/atom-armv7l/apm/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/root/atom-armv7l/apm/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
child_process.js:504
    throw err;
    ^

Error: Command failed: /root/atom-armv7l/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:481:13)
    at Object.execFileSync (child_process.js:501:13)
    at module.exports (/root/atom-armv7l/script/lib/install-atom-dependencies.js:15:16)
    at Object.<anonymous> (/root/atom-armv7l/script/bootstrap:28:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
root@localhost:~/atom-armv7l#
```
## What can I do now? Please help

**Comment by hypersad** [comment]
Try to build under user, not under root.

**Comment by Anan5a** [comment]
solved this by creating symlink. but now having different problem.
``` Module version mistatch. 46 expected. Got 48```

**Comment by hypersad** [comment]
Use electron-rebuild to rebuild this package.

**Comment by hypersad** [comment]
Use electron-rebuild to rebuild this package.

**Comment by Anan5a** [comment]
Can I delete ~/atom-armv7l after building debian package from it?

**Comment by djarami** [comment]
Yes, you should be able to.  I assume you would have installed it.

**Comment by Anan5a** [comment]
Problem solved. Successfully built and running smoothly .
![img_20170515_141433](https://cloud.githubusercontent.com/assets/16373480/26064726/9e7b844a-39b3-11e7-93d0-cdedcf4b27af.JPG)
## Thank you
