### ISSUE TITLE
Installation fails at ¨Installing autocomplete-plus@2.34.2 ✗ Package version: 2.34.2 not found¨

### ISSUE THREAD

**Issue by MrEvilCookie** [hypersad/atom-armv7l#2]
Running raspbian 8 on raspberry pi 3 model b. When it installs autocomplete-plus it stops with this error:
Installing autocomplete-plus@2.34.2 ✗
Package version: 2.34.2 not found
child_process.js:504
    throw err;
    ^

Error: Command failed: /home/pi/atom/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:481:13)
    at Object.execFileSync (child_process.js:501:13)
    at module.exports (/home/pi/atom/script/lib/install-atom-dependencies.js:15:16)
    at Object.<anonymous> (/home/pi/atom/script/bootstrap:28:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by MrEvilCookie** [comment]
full screenshot with details: 
![2018-01-09-191454_1824x984_scrot](https://user-images.githubusercontent.com/20132158/34733574-8112c7f4-f571-11e7-984f-843e31b46e4d.png)

**Comment by MrEvilCookie** [comment]
EDIT 2: Looks like it cloned previous git repo (maybe didn´t copy new link). Now building exactly this one

**Comment by MrEvilCookie** [comment]
even more errors now:
`Node:	v6.10.2
Npm:	v5.3.0
Installing script dependencies
/home/pi/atom/script/node_modules/electron-chromedriver/download-chromedriver.js:16
  if (error != null) throw error
                     ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TLSWrap.onread (net.js:572:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-chromedriver@1.6.0 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-chromedriver@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-01-09T18_30_22_883Z-debug.log
child_process.js:504
    throw err;
    ^

Error: Command failed: /home/pi/atom/script/node_modules/.bin/npm --loglevel=error install
/home/pi/atom/script/node_modules/electron-chromedriver/download-chromedriver.js:16
  if (error != null) throw error
                     ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TLSWrap.onread (net.js:572:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-chromedriver@1.6.0 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-chromedriver@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-01-09T18_30_22_883Z-debug.log

    at checkExecSyncError (child_process.js:481:13)
    at Object.execFileSync (child_process.js:501:13)
    at module.exports (/home/pi/atom/script/lib/install-script-dependencies.js:9:16)
    at Object.<anonymous> (/home/pi/atom/script/bootstrap:28:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
`

**Comment by hypersad** [comment]
Looks like it is a problem with `apm` or `autocomplete-plus` package itself. I'm gonna look in it.

**Comment by hypersad** [comment]
Hmm... Seems like this package really didn't exist. But `atom@1.23.3` uses `autocomplete-plus@2.40.0`. Could you tell me version of `atom` that you're buildibg from `atom/package.json`?

**Comment by hypersad** [comment]
So there is no problem with `autocomplete-plus` now?

**Comment by MrEvilCookie** [comment]
Well after cloning this repo instead of previous (which was https://github.com/acruzpr/atom) I can't even get till that part! Now it fails at building apm

**Comment by MrEvilCookie** [comment]
Maybe I'm doing something wrong, because I saw other people building it and running

**Comment by hypersad** [comment]
Please, read `README.md` carefully and follow it step by step. If you encounter any error during the build, post screenshot here.

**Comment by hypersad** [comment]
Closed due to inactivity.

**Comment by MrEvilCookie** [comment]
Sorry for inactivity. My old SDcard died so I had to buy new and re-install system. Now I will try doing what you said on new, clean OS

**Comment by hypersad** [comment]
Closed due to inactivity.

**Comment by MrEvilCookie** [comment]
I exactly followed README.md and got this error now: https://paste.ee/p/3B1Yt

**Comment by hypersad** [comment]
@MrEvilCookie install basic prerequisites as it described in [Atom Flight Manual](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#building). I've just forgot to add this to README.md, sorry :^)

**Comment by MrEvilCookie** [comment]
first error after a long time:
Installing open-on-github@1.3.1 ✓
Installing package-generator@1.1.1 ✗
Request for package information failed: getaddrinfo ENOTFOUND atom.io atom.io:443 (ENOTFOUND)
child_process.js:595
    throw err;
    ^

Error: Command failed: /home/pi/atom/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:574:11)
    at Object.execFileSync (child_process.js:592:13)
    at module.exports (/home/pi/atom/script/lib/run-apm-install.js:14:16)
    at Object.<anonymous> (/home/pi/atom/script/bootstrap:35:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)

**Comment by hypersad** [comment]
@MrEvilCookie what is version of Atom in your `package.json` file?

**Comment by MrEvilCookie** [comment]
Another error:
Installing language-yaml@0.31.1 ✓
Wrote Dependencies Fingerprint: /home/pi/atom/node_modules/.dependencies-fingerprint a537647a3ed0cb15f99202b489de2d9b9253596f
Running electron-packager on /home/pi/atom/out/app with app name "atom"
Downloading tmp-9264-1-SHASUMS256.txt-1.6.15
[============================================>] 100.0% of 2.96 kB (2.96 kB/s)
Packaging app for platform linux armv7l using electron v1.6.15
/home/pi/atom/script/lib/package-application.js:142
        throw new Error(err)
        ^

Error: Error: ENOENT: no such file or directory, lstat '/home/pi/atom/out/app'
  at electronPackager (/home/pi/atom/script/lib/package-application.js:142:15)
  at Immediate.<anonymous> (/home/pi/atom/script/node_modules/nodeify/index.js:19:9)
  at runCallback (timers.js:756:18)
  at tryOnImmediate (timers.js:717:5)
  at processImmediate [as _immediateCallback] (timers.js:697:5)

**Comment by hypersad** [comment]
@MrEvilCookie I'm still interested in your Atom version from `package.json` file.

**Comment by MrEvilCookie** [comment]
Contents of package.json:
{
  "name": "atom-bundled-apm",
  "description": "Atom's bundled apm",
  "repository": {
    "type": "git",
    "url": "https://github.com/atom/atom.git"
  },
  "dependencies": {
    "atom-package-manager": "1.18.12"
  }
}

**Comment by hypersad** [comment]
> Error: Error: ENOENT: no such file or directory, lstat '/home/pi/atom/out/app'

This probably happened because you're used `--existing-binaries` flag, but assets weren't been compiled. You should start building without any flags. Don't forgot to remove `apm/package-lock.json` to prevent some problems.

**Comment by MrEvilCookie** [comment]
Thanks, will try now

**Comment by MrEvilCookie** [comment]
It just crashed with out of memory error, restarting

**Comment by MrEvilCookie** [comment]
And I have a question: When it finally will be 100% done, will icon appear in start menu or I will need to somehow add it manually?

**Comment by hypersad** [comment]
You should add it somehow manually. You also could use `--install` flag, but I'm not suere that it will work.

**Comment by MrEvilCookie** [comment]
I have a feeling that its almost done, but here´s another error:
Installing modules ✓
Wrote Dependencies Fingerprint: /home/pi/atom/node_modules/.dependencies-fingerprint a537647a3ed0cb15f99202b489de2d9b9253596f
Running electron-packager on /home/pi/atom/out/app with app name "atom"
Packaging app for platform linux armv7l using electron v1.6.15
Changing permissions for node files in /home/pi/atom/out/atom-1.23.3-armv7l
Copying non-ASAR resources to /home/pi/atom/out/atom-1.23.3-armv7l/resources
Writing LICENSE.md to /home/pi/atom/out/atom-1.23.3-armv7l/resources
Application bundle created at /home/pi/atom/out/atom-1.23.3-armv7l
Generating snapshot script at "/home/pi/atom/out/startup.js" (876)Unable to transform source code for module /home/pi/atom/out/app/node_modules/winreg/lib/registry.js.
Error: /home/pi/atom/out/app/node_modules/winreg/lib/registry.js
Cannot replace with lazy function because the supplied node does not belong to an assignment expression or a variable declaration!
  at FileRequireTransform.replaceAssignmentOrDeclarationWithLazyFunction (/home/pi/atom/script/node_modules/electron-link/lib/file-require-transform.js:180:11)
  at Context.visitIdentifier (/home/pi/atom/script/node_modules/electron-link/lib/file-require-transform.js:72:18)
  at Context.invokeVisitorMethod (/home/pi/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:344:49)
  at Visitor.PVp.visitWithoutReset (/home/pi/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:196:32)
  at visitChildren (/home/pi/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/pi/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/pi/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/pi/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/pi/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/pi/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at NodePath.each (/home/pi/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path.js:101:26)
  at visitChildren (/home/pi/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:219:18)
  at Visitor.PVp.visitWithoutReset (/home/pi/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/pi/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/pi/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at visitChildren (/home/pi/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:246:25)
  at Visitor.PVp.visitWithoutReset (/home/pi/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:204:20)
  at Visitor.PVp.visit (/home/pi/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:133:29)
  at Object.visit (/home/pi/atom/script/node_modules/electron-link/node_modules/ast-types/lib/path-visitor.js:101:55)
  at FileRequireTransform.replaceDeferredRequiresWithLazyFunctions (/home/pi/atom/script/node_modules/electron-link/lib/file-require-transform.js:68:20)
  at FileRequireTransform.apply (/home/pi/atom/script/node_modules/electron-link/lib/file-require-transform.js:25:10)
  at /home/pi/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:53:56
  at Generator.next (<anonymous>:null:null)
  at step (/home/pi/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:191)
  at /home/pi/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:361
  at <anonymous>:null:null

**Comment by hypersad** [comment]
That is very interesting. I'm also encountering with this, but in another file. I'll try to investigate.

**Comment by MrEvilCookie** [comment]
If there will be any way to fix this tell me

**Comment by daphil19** [comment]
+1 on the lazy function error. Building in Ubuntu on my Asus Chrome Flip.

**Comment by MrEvilCookie** [comment]
I even tried reinstalling node, npm, all packages, that I installed from atom flight manual, tried rebuilding and still same error

**Comment by hypersad** [comment]
Build on 1.25-dev suceeded but I can't just switch patch version because there is currently no stable release and something can quickly change.

**Comment by MrEvilCookie** [comment]
Atom 1.25 beta released. Is it possible now?

**Comment by hypersad** [comment]
@MrEvilCookie more important that there is new **stable** release - 1.24. I'll try to build it.

**Comment by hypersad** [comment]
1.24.0 build succeeded. I'll update this repository soon with new patch files and instructions.

**Comment by hypersad** [comment]
@MrEvilCookie repository was updated. You could try to build Atom now.
